# Generated by Django 4.2 on 2023-08-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "student_id",
                    models.CharField(max_length=25, primary_key=True, serialize=False),
                ),
                ("student_first_name", models.CharField(max_length=256)),
                ("student_last_name", models.CharField(max_length=256)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "student",
            },
        ),
    ]
